theme: jekyll-theme-cayman
title: Compendium of Items for Baldurs Gate Enhanced Editions
description: An indepth description of all items available within Baldurs Gate Enhanced Editions
customjs:
 - https://raw.githubusercontent.com/Mottie/GitHub-userscripts/master/github-sort-content.user.js
